// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hr_crm.Data;

#nullable disable

namespace hr_crm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304124434_FixEnumStorage")]
    partial class FixEnumStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AttendanceId");

                    b.HasIndex("UserId", "AttendanceDate")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("BudgetChangeRequest", b =>
                {
                    b.Property<int>("BudgetChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetChangeRequestId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BudgetChangeRequestId");

                    b.ToTable("BudgetChangeRequests");
                });

            modelBuilder.Entity("EmployeeOnboarding", b =>
                {
                    b.Property<int>("EmployeeOnboardingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeOnboardingId"));

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChildrenDetails")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FatherAge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FatherDOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FatherDOD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsFatherDeceased")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsMotherDeceased")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LaptopImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LaptopSerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MotherAge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MotherDOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MotherDOD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeMobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SpouseDOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpouseName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemporaryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeOnboardingId");

                    b.ToTable("EmployeeOnboardings");
                });

            modelBuilder.Entity("EmployeeOnboardingDocuments", b =>
                {
                    b.Property<int>("EmployeeOnboardingDocumentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeOnboardingDocumentsId"));

                    b.Property<string>("AadharCardPath")
                        .HasColumnType("text");

                    b.Property<string>("AcceptanceLetterPath")
                        .HasColumnType("text");

                    b.Property<string>("BankPassbookPath")
                        .HasColumnType("text");

                    b.Property<string>("BankStatementPath")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeOnboardingId")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceLetterPath")
                        .HasColumnType("text");

                    b.Property<string>("HighestQualificationDocumentPath")
                        .HasColumnType("text");

                    b.Property<string>("PANCardPath")
                        .HasColumnType("text");

                    b.Property<string>("ParentAadharPaths")
                        .HasColumnType("text");

                    b.HasKey("EmployeeOnboardingDocumentsId");

                    b.ToTable("EmployeeOnboardingDocuments");
                });

            modelBuilder.Entity("EmployeeOnboardingWorkExperience", b =>
                {
                    b.Property<int>("EmployeeOnboardingWorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeOnboardingWorkExperienceId"));

                    b.Property<int>("EmployeeOnboardingId")
                        .HasColumnType("integer");

                    b.Property<string>("LastCompanyPFNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastCompanyUAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferedDesignation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OfferedMonthlyCTC")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OfferedSalaryNTH")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OfferedYearlyCTC")
                        .HasColumnType("numeric");

                    b.Property<string>("PreviousCompanyDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousCompanyPayslipPath")
                        .HasColumnType("text");

                    b.Property<string>("TotalExperience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeOnboardingWorkExperienceId");

                    b.ToTable("EmployeeOnboardingWorkExperiences");
                });

            modelBuilder.Entity("OvertimeApproval", b =>
                {
                    b.Property<int>("OvertimeApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OvertimeApprovalId"));

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OvertimeApprovalId");

                    b.ToTable("OvertimeApprovals");
                });

            modelBuilder.Entity("OvertimeRecord", b =>
                {
                    b.Property<int>("OvertimeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OvertimeRecordId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OvertimeHours")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OvertimeRecordId");

                    b.ToTable("OvertimeRecords");
                });

            modelBuilder.Entity("Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShiftId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("ShiftId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("UserShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("UserShifts");
                });

            modelBuilder.Entity("hr_crm.Entities.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("hr_crm.Entities.BudgetGuideline", b =>
                {
                    b.Property<int>("BudgetGuidelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BudgetGuidelineId"));

                    b.Property<decimal>("MaxAnnualBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxResourcePercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxTrainingPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("BudgetGuidelineId");

                    b.ToTable("BudgetGuidelines");
                });

            modelBuilder.Entity("hr_crm.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.HasIndex("BranchId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("hr_crm.Entities.DepartmentBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("FinanceApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinanceApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HeadApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HeadApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ResourceBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAnnualBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TrainingBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsedBudget")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentBudgets");
                });

            modelBuilder.Entity("hr_crm.Entities.DepartmentRole", b =>
                {
                    b.Property<int>("DepartmentRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentRoleId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("PerformanceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredSkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentRoleId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentRoles");
                });

            modelBuilder.Entity("hr_crm.Entities.Knowledge", b =>
                {
                    b.Property<int>("KnowledgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KnowledgeId"));

                    b.Property<string>("ApporvedBy")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("text");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordType")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .HasColumnType("text");

                    b.HasKey("KnowledgeId");

                    b.HasIndex("BranchId");

                    b.ToTable("Knowledges");
                });

            modelBuilder.Entity("hr_crm.Entities.OvertimePolicy", b =>
                {
                    b.Property<int>("OvertimePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OvertimePolicyId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<double>("MaxWeeklyOvertimeHours")
                        .HasColumnType("double precision");

                    b.Property<double>("StandardDailyHours")
                        .HasColumnType("double precision");

                    b.HasKey("OvertimePolicyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("OvertimePolicies");
                });

            modelBuilder.Entity("hr_crm.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("hr_crm.Entities.Recruitment", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateId"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<string>("AppliedPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidateId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Recruitments");
                });

            modelBuilder.Entity("hr_crm.Entities.TodoTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId");

                    b.ToTable("TodoTasks");
                });

            modelBuilder.Entity("hr_crm.Entities.UserDepartmentRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentRoleId");

                    b.ToTable("UserDepartmentRoles");
                });

            modelBuilder.Entity("Shift", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UserShift", b =>
                {
                    b.HasOne("Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("hr_crm.Entities.Department", b =>
                {
                    b.HasOne("hr_crm.Entities.Branch", "Branch")
                        .WithMany("Departments")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("hr_crm.Entities.DepartmentBudget", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany("Budgets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("hr_crm.Entities.DepartmentRole", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("hr_crm.Entities.Knowledge", b =>
                {
                    b.HasOne("hr_crm.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("hr_crm.Entities.OvertimePolicy", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("hr_crm.Entities.Project", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("hr_crm.Entities.Recruitment", b =>
                {
                    b.HasOne("hr_crm.Entities.Department", "Department")
                        .WithMany("Recruitments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("hr_crm.Entities.UserDepartmentRole", b =>
                {
                    b.HasOne("hr_crm.Entities.DepartmentRole", "DepartmentRole")
                        .WithMany("UserDepartmentRoles")
                        .HasForeignKey("DepartmentRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentRole");
                });

            modelBuilder.Entity("hr_crm.Entities.Branch", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("hr_crm.Entities.Department", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Projects");

                    b.Navigation("Recruitments");
                });

            modelBuilder.Entity("hr_crm.Entities.DepartmentRole", b =>
                {
                    b.Navigation("UserDepartmentRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
