using System;
using hr_crm.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace hr_crm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403120000_AddAuthUsersTable")]
    public class AddAuthUsersTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS users (
                    user_id integer GENERATED BY DEFAULT AS IDENTITY,
                    employee_id text NULL,
                    username text NULL,
                    emails text NULL,
                    department text NULL,
                    designation text NULL,
                    manager_id integer NULL,
                    assigned_team_id integer NULL,
                    assigned_region text NULL,
                    assigned_branch text NULL,
                    account_status text NULL,
                    lock_reason text NULL,
                    access_start_date timestamp with time zone NULL,
                    access_end_date timestamp with time zone NULL,
                    last_activity_at timestamp with time zone NULL,
                    last_assigned_lead_at timestamp with time zone NULL,
                    last_closed_ticket_at timestamp with time zone NULL,
                    employment_type text NULL,
                    work_shift text NULL,
                    terms_accepted_at timestamp with time zone NULL,
                    remarks text NULL,
                    created_by integer NULL,
                    updated_by integer NULL,
                    approved_by integer NULL,
                    security_reviewed_by integer NULL,
                    created_at timestamp with time zone NULL,
                    updated_at timestamp with time zone NULL,
                    deleted_at timestamp with time zone NULL,
                    created_via text NULL,
                    "DomainId" integer NULL,
                    "Gender" text NULL,
                    payroll_amount numeric NULL,
                    CONSTRAINT "PK_users" PRIMARY KEY (user_id)
                );
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS users;");
        }
    }
}
